version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  mysql:
    networks:
      - app-network
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notification_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    networks:
      - app-network
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "5d8ec0267667e9e2fde03bdf08b8094ca0010ca90f5ba77c1507d99534cf3866!#@#!551231asdfacas!@#%$#%@"
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  mongodb:
    networks:
      - app-network
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mysql-data:
  mongo-data:
  rabbitmq_data:
